server:
  port: 5555
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
     
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cardservice
        uri: lb://cardservice
        predicates:
        - Path=/card/**
        filters:
        - RewritePath=/card/(?<path>.*), /$\{path}
      - id: medicineservice
        uri: lb://medicineservice
        predicates:
        - Path=/medicine/**
        filters:
        - RewritePath=/medicine/(?<path>.*), /$\{path}
      - id: prescriptionservice
        uri: lb://prescriptionservice
        predicates:
        - Path=/prescription/**  
        filters:
        - RewritePath=/prescription/(?<path>.*), /$\{path}
  zipkin:
    locator:
      discovery:
        enabled: true
    baseUrl: http://localhost:9411
    sender:
      type: web
  sleuth:
    enabled: true
    http: 
       legacy:
          enabled: true
    sampler:
      percentage: 1.0