server:
  port: 8081
  
spring:
  zipkin:
    locator:
      discovery:
        enabled: true
    baseUrl: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0
 
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        